set_property IOSTANDARD LVCMOS33 [get_ports audio_lrclk]
set_property IOSTANDARD LVCMOS33 [get_ports audio_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports audio_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports audio_sdin]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN A16 [get_ports audio_lrclk]
set_property PACKAGE_PIN A14 [get_ports audio_mclk]
set_property PACKAGE_PIN B15 [get_ports audio_sclk]
set_property PACKAGE_PIN B16 [get_ports audio_sdin]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN V17 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]

set_property PACKAGE_PIN L1 [get_ports {count[3]}]
set_property PACKAGE_PIN P1 [get_ports {count[2]}]
set_property PACKAGE_PIN N3 [get_ports {count[1]}]
set_property PACKAGE_PIN P3 [get_ports {count[0]}]
